name: Build Add-on and Upload Artifact

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the add-on package
        run: bash ./docker-create-zip.sh

      - name: Upload add-on artifact
        uses: actions/upload-artifact@v4
        with:
          name: autowwwleak-unsigned
          path: autowwwleak.zip
