name: Build Add-on and Upload Artifact

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Zip source code
        run: zip -r autowwwtest-src.zip . -x ".git/*"

      - name: Upload source code artifact
        uses: actions/upload-artifact@v4
        with:
          name: autowwwtest-source-code
          path: autowwwtest-src.zip

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the add-on package
        run: bash ./docker-create-zip.sh

      - name: Upload add-on artifact
        uses: actions/upload-artifact@v4
        with:
          name: autowwwtest-unsigned-build
          path: autowwwtest.zip
